matrix:
  include:
    - language: python
      python:
        - 3.7
      before_install:
        - cd backend/
      install:
        - pip install -r requirements.txt
        - pip install docker-compose
      services:
        - docker
      script:
        - docker-compose run backend sh -c "pytest && flake8"
#    - language: node_js
#      node_js:
#        - 10.16
#      before_install:
#        - cd frontend/
#      install:
#        - yarn install
#      script:
#        - yarn test

notifications:
  email: false