# Generated by Django 3.0.1 on 2019-12-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191229_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='test', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
